### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'set')

### ISSUE THREAD

**Issue by gwynnbleiidd** [lebestnoob/webtorio-ddl#3]
Hi, when trying to add a magnet

```
TypeError: Cannot read properties of undefined (reading 'set')
    at Context.set res (file:///node_modules/.deno/hono@4.5.4/node_modules/hono/dist/context.js:71:24)
    at dispatch (file:///node_modules/.deno/hono@4.5.4/node_modules/hono/dist/compose.js:43:21)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async compress2 (file:///node_modules/.deno/hono@4.5.4/node_modules/hono/dist/middleware/compress/index.js:5:5)
    at async dispatch (file:///node_modules/.deno/hono@4.5.4/node_modules/hono/dist/compose.js:29:17)
    at async file:///src/main.js:14:5
    at async dispatch (file:///node_modules/.deno/hono@4.5.4/node_modules/hono/dist/compose.js:29:17)
    at async file:///node_modules/.deno/hono@4.5.4/node_modules/hono/dist/hono-base.js:200:25
    at async ext:deno_http/00_serve.ts:364:18
```
    
sample
    
`magnet:?xt=urn:btih:d0a768fe38a853131898d10593e4af62dad35103&dn=Despicable Me 4 (2024) TS AVC Ukr.mkv&tr=http://bt.toloka.to/announce/?h=ZhAYIckJW3&&tr=http://bt.hurtom.com/announce/?h=ZhAYIckJW3&&tr=http://bt.toloka.tv/announce/?h=ZhAYIckJW3&`

**Comment by lebestnoob** [comment]
Please try it now. The patch I made should work
